import type { SnapshotParams } from "@/lib/validations";
import type { Snapshot } from "@/server/db/schema";

export function paramsToDb(p: SnapshotParams) {
  return {
    coalPrice: String(p.coalPrice),
    discRate: String(p.discRate),
    annualProd: String(p.annualProd),
    mineLife: Math.round(p.mineLife),
    cashCost: String(p.cashCost),
    royaltyRate: String(p.royaltyRate),
    taxRate: String(p.taxRate),
    capex: String(p.capex),
    measuredMt: String(p.measuredMt),
    indicatedMt: String(p.indicatedMt),
    inferredMt: String(p.inferredMt),
    measuredGar: Math.round(p.measuredGar),
    indicatedGar: Math.round(p.indicatedGar),
    inferredGar: Math.round(p.inferredGar),
    recoveryRate: String(p.recoveryRate),
    stripRatio: String(p.stripRatio),
    haulingDist: String(p.haulingDist),
    bargeDist: String(p.bargeDist),
    crushCost: String(p.crushCost),
    portHandling: String(p.portHandling),
    acquisitionCost: String(p.acquisitionCost),
    debtPct: String(p.debtPct),
    debtCost: String(p.debtCost),
    loanTenor: Math.round(p.loanTenor),
    sharedInfra: Math.round(p.sharedInfra),
    gaConsolidation: String(p.gaConsolidation),
    procSavings: String(p.procSavings),
    iupValid: p.iupValid,
    certClean: p.certClean,
    amdal: p.amdal,
    ppa: p.ppa,
    dmb: p.dmb,
  };
}

export function rowToParams(row: Snapshot): SnapshotParams {
  const n = (v: string | null) => Number(v ?? 0);
  return {
    coalPrice: n(row.coalPrice),
    discRate: n(row.discRate),
    annualProd: n(row.annualProd),
    mineLife: row.mineLife,
    cashCost: n(row.cashCost),
    royaltyRate: n(row.royaltyRate),
    taxRate: n(row.taxRate),
    capex: n(row.capex),
    measuredMt: n(row.measuredMt),
    indicatedMt: n(row.indicatedMt),
    inferredMt: n(row.inferredMt),
    measuredGar: row.measuredGar,
    indicatedGar: row.indicatedGar,
    inferredGar: row.inferredGar,
    recoveryRate: n(row.recoveryRate),
    stripRatio: n(row.stripRatio),
    haulingDist: n(row.haulingDist),
    bargeDist: n(row.bargeDist),
    crushCost: n(row.crushCost),
    portHandling: n(row.portHandling),
    acquisitionCost: n(row.acquisitionCost),
    debtPct: n(row.debtPct),
    debtCost: n(row.debtCost),
    loanTenor: row.loanTenor,
    sharedInfra: row.sharedInfra,
    gaConsolidation: n(row.gaConsolidation),
    procSavings: n(row.procSavings),
    iupValid: row.iupValid,
    certClean: row.certClean,
    amdal: row.amdal,
    ppa: row.ppa,
    dmb: row.dmb,
  };
}
