import { z } from "zod";

export const snapshotParamsSchema = z.object({
  coalPrice: z.number().min(50).max(250),
  discRate: z.number().min(5).max(25),
  annualProd: z.number().min(1).max(20),
  mineLife: z.number().min(5).max(40),
  cashCost: z.number().min(0),
  royaltyRate: z.number().min(0).max(15),
  taxRate: z.number().min(10).max(35),
  capex: z.number().min(50).max(500),
  measuredMt: z.number().min(0),
  indicatedMt: z.number().min(0),
  inferredMt: z.number().min(0),
  measuredGar: z.number().min(0),
  indicatedGar: z.number().min(0),
  inferredGar: z.number().min(0),
  recoveryRate: z.number().min(50).max(100),
  stripRatio: z.number().min(1).max(20),
  haulingDist: z.number().min(5).max(150),
  bargeDist: z.number().min(50).max(500),
  crushCost: z.number().min(1).max(8),
  portHandling: z.number().min(1).max(10),
  acquisitionCost: z.number().min(50).max(500),
  debtPct: z.number().min(0).max(80),
  debtCost: z.number().min(3).max(20),
  loanTenor: z.number().min(1).max(10),
  sharedInfra: z.number().min(1).max(30),
  gaConsolidation: z.number().min(0).max(80),
  procSavings: z.number().min(0).max(25),
  iupValid: z.boolean(),
  certClean: z.boolean(),
  amdal: z.boolean(),
  ppa: z.boolean(),
  dmb: z.boolean(),
});

export type SnapshotParams = z.infer<typeof snapshotParamsSchema>;

export const defaultSnapshotParams: SnapshotParams = {
  coalPrice: 120,
  discRate: 10,
  annualProd: 5,
  mineLife: 20,
  cashCost: 24,
  royaltyRate: 7,
  taxRate: 22,
  capex: 180,
  measuredMt: 50,
  indicatedMt: 40,
  inferredMt: 20,
  measuredGar: 5400,
  indicatedGar: 5200,
  inferredGar: 4900,
  recoveryRate: 85,
  stripRatio: 6,
  haulingDist: 35,
  bargeDist: 180,
  crushCost: 2.5,
  portHandling: 3.5,
  acquisitionCost: 120,
  debtPct: 60,
  debtCost: 8,
  loanTenor: 5,
  sharedInfra: 12,
  gaConsolidation: 30,
  procSavings: 8,
  iupValid: true,
  certClean: true,
  amdal: true,
  ppa: false,
  dmb: true,
};

export const extractionResultSchema = z.object({
  reservesMt: z.number().nullable(),
  measuredMt: z.number().nullable(),
  indicatedMt: z.number().nullable(),
  inferredMt: z.number().nullable(),
  coalGarAvg: z.number().nullable(),
  cashCostEstimate: z.number().nullable(),
  annualRevenue: z.number().nullable(),
  ebitda: z.number().nullable(),
  netAssets: z.number().nullable(),
  iupStatus: z.string().nullable(),
  environmentalStatus: z.string().nullable(),
  complianceFlags: z.object({
    iupValid: z.boolean(),
    certClean: z.boolean(),
    amdal: z.boolean(),
    ppa: z.boolean(),
    dmb: z.boolean(),
  }),
  confidence: z.number().min(0).max(100),
});

export type ExtractionResult = z.infer<typeof extractionResultSchema>;
